apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mrdevops
  template:
    metadata:
      labels:
        app: mrdevops
    spec:
      containers:
        - name: mrdevops
          image: rahulkumar9536/flipkart-dev:v1.20
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  selector:
    app: mrdevops
  type: NodePort          # Use NodePort for Minikube
  ports:
    - port: 80            # Service port
      targetPort: 80      # Container port
      nodePort: 31200     # NodePort to access externally
