apiVersion: v1
kind: Service
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  selector:
    app: mrdevops
  type: NodePort        # Changed from LoadBalancer for Minikube
  ports:
    - port: 80           # Service port
      targetPort: 80     # Pod container port
      nodePort: 31091    # NodePort to access the service externally
